In [1]:
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.data.load_data import load_csv_data

In [2]:
df=load_csv_data("../data/processed/train_cleaned.csv")

Data loaded successfully from ../data/processed/train_cleaned.csv
Data shape: (1460, 81)

In [3]:
df["HouseAge"] = (
    df["YrSold"] -
    df["YearBuilt"]
)

In [4]:
df[
    ["YearBuilt",
     "YrSold",
     "HouseAge"]
].head()

   YearBuilt  YrSold  HouseAge
0       2003    2008         5
1       1976    2007        31
2       2001    2008         7
3       1915    2006        91
4       2000    2008         8

In [5]:
df["TotalBathrooms"] = (
    df["FullBath"]
    + 0.5 * df["HalfBath"]
    + df["BsmtFullBath"]
    + 0.5 * df["BsmtHalfBath"]
)

In [6]:
df[
    [
        "FullBath",
        "HalfBath",
        "BsmtFullBath",
        "BsmtHalfBath",
        "TotalBathrooms"
    ]
].head()

   FullBath  HalfBath  BsmtFullBath  BsmtHalfBath  TotalBathrooms
0         2         1             1             0             3.5
1         2         0             0             1             2.5
2         2         1             1             0             3.5
3         1         0             1             0             2.0
4         2         1             1             0             3.5

In [9]:
df["TotalSquareFeet"] = (
    df["TotalBsmtSF"]
    + df["1stFlrSF"]
    + df["2ndFlrSF"]
)

In [10]:
df[
    [
        "TotalBsmtSF",
        "1stFlrSF",
        "2ndFlrSF",
        "TotalSquareFeet"
    ]
].head()

   TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSquareFeet
0          856       856       854             2566
1         1262      1262         0             2524
2          920       920       866             2706
3          756       961       756             2473
4         1145      1145      1053             3343

In [11]:
new_features = [
    "HouseAge",
    "TotalBathrooms",
    "TotalSquareFeet"
]

df[new_features].describe()

          HouseAge  TotalBathrooms  TotalSquareFeet
count  1460.000000     1460.000000      1460.000000
mean     36.547945        2.210616      2567.048630
std      30.250152        0.785399       821.714421
min       0.000000        1.000000       334.000000
25%       8.000000        2.000000      2009.500000
50%      35.000000        2.000000      2474.000000
75%      54.000000        2.500000      3004.000000
max     136.000000        6.000000     11752.000000